// Emits `app/lib/api/generated/contract.gen.ts` — app-facing contract types inferred (`z.infer`) from
// the generated Zod schemas (#17), so types and runtime validation share one source and app code never
// imports the static `types.gen.ts`. Run via `tsx` as the last step of `api:generate`; output is
// git-ignored and must not be hand-edited (ADR-0010). No runtime deps — reads the names from `zod.gen.ts`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const generatedDir = resolve(dirname(fileURLToPath(import.meta.url)), "../app/lib/api/generated");
const source = readFileSync(resolve(generatedDir, "zod.gen.ts"), "utf8");

// Every exported `z<Name>` schema → `export type <Name> = z.infer<typeof schemas.z<Name>>`.
const schemaNames = [...source.matchAll(/^export const (z[A-Z]\w*)\b/gm)].map((match) => match[1]);
const unique = [...new Set(schemaNames)].sort();

const contents = [
  "// AUTO-GENERATED by scripts/generate-contract-types.ts (via `api:generate`) — do not edit.",
  "// App-facing contract types inferred from the generated Zod schemas (#17). Never import the",
  "// static `types.gen.ts` in app code; import these (or re-exports from `api.server.ts`) instead.",
  'import type { z } from "zod";',
  'import * as schemas from "./zod.gen";',
  "",
  ...unique.map((name) => `export type ${name.slice(1)} = z.infer<typeof schemas.${name}>;`),
  "",
].join("\n");

writeFileSync(resolve(generatedDir, "contract.gen.ts"), contents);
console.log(`Generated ${unique.length} contract types → app/lib/api/generated/contract.gen.ts`);
